[build]
builder = "NIXPACKS"
buildCommand = "cd Backend && npm install && cp -r ../Frontend ."

[deploy]
startCommand = "cd Backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
